version: "3"

services:
        hbase:
                image: dajobe/hbase
                ports:
                        - 2181:2182
        bigtable:
                image: shopify/bigtable-emulator
                ports:
                        - 9035:9035
        test:
                build: .
                entrypoint: "/perftest.sh"
                depends_on:
                        - hbase
                        - bigtable
                environment:
                        - ZOOKEEPER_QUORUM=hbase
                        - ZOOKEEPER_PORT=2181
                        - BIGTABLE_PROJECT_ID=project-id
                        - BIGTABLE_INSTANCE_ID=instance-id
                        - BIGTABLE_EMULATOR_HOST=bigtable:9035
                volumes:
                        - ./results:/results
